apiVersion: 1
datasources:
  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger-query:16686
    readOnly: false
    editable: true
    jsonData:
      tracesToLogs:
        # Field with internal link pointing to a logs data source in Grafana.
        # datasourceUid value must match the datasourceUid value of the logs data source.
        datasourceUid: 'grafana'
        filterByTraceID: true
        filterBySpanID: false
      nodeGraph:
        enableNodeGraph: true


